- name: Cluster startup process
  block:
    - name: Start primary MySQL node with Bootstrap
      ansible.builtin.shell: |
        nohup sudo -u mysql mysqld --wsrep-new-cluster --user=mysql --log-error=/var/log/mysql/error.log > /dev/null 2>&1 &
      args:
        executable: /bin/bash
      async: 10
      poll: 0
      register: bootstrap_status
      tags: bootstrap_cluster
      when: inventory_hostname in groups['mysql_primary']

    - name: Wait 10 seconds after starting the primary node
      ansible.builtin.pause:
        seconds: 10
      tags: bootstrap_cluster
      when: inventory_hostname in groups['mysql_primary']

    - name: Check cluster status as MySQL user
      ansible.builtin.shell: >
        mysql -e "
        SHOW STATUS LIKE 'wsrep_cluster_state_uuid';
        SHOW STATUS LIKE 'wsrep_local_state_comment';
        SHOW STATUS LIKE 'wsrep_cluster_size';"
      become: yes
      become_user: mysql
      register: cluster_status
      changed_when: false
      tags: bootstrap_cluster
      when: inventory_hostname in groups['mysql_primary']

    - name: Display cluster status
      ansible.builtin.debug:
        msg: "{{ cluster_status.stdout_lines }}"
      tags: bootstrap_cluster
      when: inventory_hostname in groups['mysql_primary']

  always:
    - name: Start secondary nodes
      ansible.builtin.systemd:
        name: mysql
        state: started
      when: inventory_hostname in groups['mysql_secondary']
      tags: start_secondary_nodes
